# http://travis-ci.org/#!/mozilla/peekaboo

# This indicates to Travis that we will not use or need sudo
# so that we can benefit from and use the cache->directories
# directive.
sudo: no

env: PIP_DOWNLOAD_CACHE="pip_cache"
cache:
    directories:
        - pip_cache

language: python

python:
    - 2.7

install:
    - bin/travis/install.sh
before_script:
    - bin/travis/lint.sh
    - bin/travis/setup.sh
script:
    - bin/travis/test.sh
